### ISSUE TITLE
allow to create containers with the `host` networking 

### ISSUE THREAD

**Issue by hellt** [srl-wim/container-lab#211]
https://docs.docker.com/network/host/

I propose to expose this setting (string) on the node level only for now

```yaml
  nodes:
    telegraf:
      kind: linux
      network: host
```

the user-defined IP addresses and exposed ports will not have effect with host networking.
