### ISSUE TITLE
bind mount directories should be possible to set per kind and node

### ISSUE THREAD

**Issue by hellt** [srl-wim/container-lab#88]
To allow mounting files to the containerlab modes, the `mount` option have to be created for kinds and nodes.
The use case is to add custom binaries or configs for testing containers (like adding gobgp to a vanilla alpine)

```yaml
kind_defaults:
    my_tools:
      type: custom
      image: pklepikov/ubuntu-tools
      mounts:
       - $(pwd)/exabgp /home/admin/exabgp
       - $(pwd)/gobgp /home/admin/gobgp
```
