### ISSUE TITLE
rework topology definition file

### ISSUE THREAD

**Issue by hellt** [srl-wim/container-lab#97]
This issue will track the design decisions on the new "topology definition" format clab should adopt.

The recent proposal was:

```yaml
name: wan-topo
mgmt:
  # network is not mandatory, if not specified it default to $name-network
  network: $name-network
  ipv4_range: <ipv4 mgmt range>
  ipv6_range: <ipv6 mgmt range>
topology:
  defaults:
    kind: srl
  kinds:
    srl:
      image: srlinux20.6.1-286
      type: ixr6
    alpine:
      image: henderiw/client-alpine:1.0.0
  
  nodes:
    node1:
    node2:
    client1:
      kind: alpine
    client2:
      kind: alpine
  
  links:
    - endpoints: [ "node1:e1-1", "node2:e1-1"]
    - endpoints: [ "node1:e1-2", "client1:eth1"]
    - endpoints: [ "node2:e1-2", "client2:eth1"]
```

The areas that we need to have a discussion on:

1. how to model endpoints/links to allow for data augmentation. For example, when we will do the config generation for interfaces, how do we add the interface-related information to the endpoints.
2. where to keep the protocol and other logical-inventory related data for config generation?
